apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-deployment
spec:
  selector:
    matchLabels:
      app: todo-app
  replicas: 2
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
      - name: todo-app
        image: todo-app:1.0.0
        imagePullPolicy: Never
        env:
          - name: API_BASE_PATH
            value: "http://host.docker.internal:5000"
        ports:
        - containerPort: 3000

